[book]
authors = ["Ankitects Pty Ltd and contributors"]
language = "en"
multilingual = false
src = "src"
title = "Changes"

[build]
create-missing = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
no-section-label = true
git-repository-url = "https://github.com/ankitects/changes/"

#[output.linkcheck]
#optional = true
#warning-policy = "warn"
#follow-web-links = true
